name: InfiniteStew
version: '${project.version}'
main: com.ashkiano.infinitestew.InfiniteStew
api-version: '1.16'
author: AshKiano
description: Plugin providing an infinite rabbit stew.
commands:
  infinitestew:
    description: Gives the player an infinite rabbit stew.
    usage: /<command>